### ISSUE TITLE
Environment on Ubuntu missing OpenCL

### ISSUE THREAD

**Issue by magnus-haw** [magnus-haw/arcjetCV#21]
(base) magnus@shadowfax:arcjetCV$ conda activate arcjetCV                                                                                              
WARNING: No ICDs were found. Either,                                                                                                                   
- Install a conda package providing a OpenCL implementation (pocl, oclgrind, intel-compute-runtime, beignet) or                                        
- Make your system-wide implementation visible by installing ocl-icd-system conda package.

We may want to add a dependency for this

**Comment by fsemerar** [comment]
I think the release on conda-forge will take care of these nuances between systems

**Comment by magnus-haw** [comment]
my fix was: conda install pocl

**Comment by magnus-haw** [comment]
solved via conda-forge
